# Generated by Django 5.2.6 on 2025-09-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
