# Generated by Django 5.2.6 on 2025-09-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_usuarios_email_usuarios_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
