# Generated by Django 5.2.6 on 2025-09-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_usuarios_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
