# Generated by Django 5.2.6 on 2025-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_usuarios_bairro_usuarios_cidade_usuarios_logradouro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
